### ISSUE TITLE
RegEx requires src to follow image

### ISSUE THREAD

**Issue by jbienzss** [raiki61/base64-image-embedder#5]
With the current RegEx the image tag must be defined so that `src` is the first parameter.

The following will work:

`<img src="Images/image002.png" ...`

The following will not work:

`<img width=624 height=351 src="Images/image002.png" ...`

**Comment by raiki61** [comment]
thank you.
I'll check it and try to fix it.

**Comment by raiki61** [comment]
Thank you for feedback.
It fixed by ver 0.0.2.
