### ISSUE TITLE
Doesn't work when folder opened

### ISSUE THREAD

**Issue by IanWitham** [raiki61/base64-image-embedder#7]
When you "open folder" with VSCode, and then from VSCode open a file, the plugin does not embed any files. It will only work if you open the file directly from the OS.

**Comment by raiki61** [comment]
I tried the following in my windows environment and it worked fine.

1. Click on the “File” menu in vscode. 
2. click on “Open Folder
3. open any folder
5. select any html file from vscode's folder tree
5. run the plugin

Do you have any other information?
As per another ticket, I will check it on Linux as soon as I get time.
